Repository adessoAG/junit-insights, pull requests merged in 2018-04, with the labels that each got.

#23 Create HTML reports instead of CSV files
  build.gradle
  src/main/kotlin/de/adesso/junitinsights/listener/SpringContextListener.kt
  src/main/kotlin/de/adesso/junitinsights/tests/TestBenchmarkExtension.kt
  src/main/kotlin/de/adesso/junitinsights/tools/TimestampWriter.kt
  src/main/resources/htmlTemplate.html
  visualization/index.html
  visualization/process_data.js
  visualization/visualize_data.js
Labels: enhancement

#24 add documentation
  .gitignore
  src/main/kotlin/de/adesso/junitinsights/JunitInsightsApplication.kt
  src/main/kotlin/de/adesso/junitinsights/annotations/JUnitInsights.kt
  src/main/kotlin/de/adesso/junitinsights/annotations/NoJUnitInsights.kt
  src/main/kotlin/de/adesso/junitinsights/example/HelloController.kt
  src/main/kotlin/de/adesso/junitinsights/listener/SpringContextListener.kt
  src/main/kotlin/de/adesso/junitinsights/tests/TestBenchmarkExtension.kt
  src/main/kotlin/de/adesso/junitinsights/tools/TimestampWriter.kt
  src/test/kotlin/de/adesso/junitinsights/AnotherHelloControllerTest.kt
  src/test/kotlin/de/adesso/junitinsights/HelloControllerTest.kt
  src/test/kotlin/de/adesso/junitinsights/NewTest.kt
Labels: documentation

#27 Add options to filter and order the list of individual test classes
  src/main/resources/htmlTemplate.html
Labels: feature

#45 Move duplicate gradle code from subprojects to superproject
  build.gradle
  library/build.gradle
  tester/build.gradle
Labels: enhancement

#46 Prevent the creation of an empty report when no test class is annotated
  library/src/main/kotlin/de/adesso/junitinsights/tools/TimestampWriter.kt
Labels: enhancement
